name: Publish Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    release:
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '17'

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v3

        - name: Publish Release
          run: ./gradlew publish